; custom radio board with EBYTE E22-900M30S LoRa module https://oshwlab.com/jljohnson87/xiaowow
[env:xiaowow_nrf52840]
extends = env:seeed_xiao_nrf52840_kit
board_level = extra
build_flags = ${env:seeed_xiao_nrf52840_kit.build_flags} 
  -D EBYTE_E22
  -D EBYTE_E22_900M30S

[env:xiaowow_nrf52840_i2c]
extends = env:seeed_xiao_nrf52840_kit_i2c
board_level = extra
build_flags = ${env:seeed_xiao_nrf52840_kit_i2c.build_flags}
  -D EBYTE_E22
  -D EBYTE_E22_900M30S